### ISSUE TITLE
상품 태깅 어드민 UI 개발

### ISSUE THREAD

**Issue by ywoo-park** [ssho-lab/ssho-issue-board#26]
- API : https://github.com/ssho-lab/ssho-api-document/wiki/어드민
- 해당 이슈에 진행 사항 공유 부탁드립니다!

**Comment by ed-jinyoung-park** [comment]
PR에 진행사항 정리했습니다. 
https://github.com/ssho-lab/ssho-admin-web/pull/4

**Comment by ed-jinyoung-park** [comment]
@ywoo-park 님 상품 태그 삭제 API 관련 질문입니다.
https://github.com/ssho-lab/ssho-api-document/wiki/%EC%83%81%ED%92%88-%ED%83%9C%EA%B7%B8-%EC%82%AD%EC%A0%9C

상품 태그 삭제 API에 요청바디로 삭제할 태그들을 넣는건가요?
혹시 그렇다면 지금 UI 상으로 X버튼을 누를떄마다 삭제요청이 가야하는데, 그렇게 되면 API call 횟수가 너무 많아질 것 같다는 생각이 듭니다.
![image](https://user-images.githubusercontent.com/26531678/96692121-a7839880-13c0-11eb-8778-fcb3adbb6512.png)

제 생각은 
1) 기존 태그리스트에서 삭제, 수정등의 변화가 있으면 '태그 수정'버튼을 활성화하고 
2) 태그 수정버튼을 누르면 현재 선택된 태그들을 요청바디로 보내 해당 아이템의 태그리스트를 그대로 업데이트(덮어씌우기)하는 것이 더 편하지 않을까 싶어서요! 
API 개발측면에서는 추가,삭제,수정 등의 API를 수정 API하나로 통합할 수 있고 
유저입장에서도 추가,삭제,수정 따로 할 것 없이 버튼 한번만 누르면 되서 편할 것 같습니다.

의견 부탁드립니다:)

**Comment by ywoo-park** [comment]
@Zinyon 
진영님 피드백에 따라 API를 새롭게 추가했습니다!

https://github.com/ssho-lab/ssho-api-document/wiki/%EC%83%81%ED%92%88-%ED%83%9C%EA%B7%B8-%EC%88%98%EC%A0%95

**Comment by ywoo-park** [comment]
@Zinyon 
API 수정에 따른 추가 구현 사항 커밋 후에 PR 하나 더 날려주세요 진영님~!
