### ISSUE TITLE
[어드민 웹] 아이템 노출 빈도 조회 API 개발

### ISSUE THREAD

**Issue by ed-jinyoung-park** [ssho-lab/ssho-issue-board#27]
### 아이템 노출 빈도 
추천시스템 평가를 위한  아이템 노출 빈도 모니터링 API를 구현한다.
측정 데이터 : 스와이프 아이템 노출 횟수
- [x] 각 아이템 당 스와이프 로그에 얼마나 찍혔는지 그 횟수를 리턴하는 API를 구현한다.
- [x] 어드민 웹 '등록 상품' 탭에 노출횟수를 칼럼으로 추가한다.

* 유저의 로그 누적 상태에 따라 추출되는 아이템이 다를 수 있으므로 로그수를 동일하게 조작하기 위해 elastic search에서 **test-log** Index를 생성해야 한다.

**Comment by ed-jinyoung-park** [comment]
@ywoo-park 영우님 elastic search에서 아이템 노출 빈도 조회값을 리턴하기 위해서 
다음과 같은 쿼리를 써서 
```
GET activity-log-swipe/_search
{
  "aggs":{
    "value_count":{
      "terms": {
        "field": "itemId"
      }
    }
  }
}
```
아래의 결과를 얻었는데요!
```
...
"buckets" : [
        {
          "key" : "0001248776",
          "doc_count" : 3
        },
        {
          "key" : "0001249185",
          "doc_count" : 3
        },
        {
          "key" : "0001247794",
          "doc_count" : 2
        },
        {
          "key" : "0001248774",
          "doc_count" : 2
        },

      ]
```



처음에 저 쿼리를 쓰려니까 text 필드는 집계, 정렬시에 따로 ``fileddata``라는 인덱싱 패턴?을 사용하는데 이게 비용이 커서 default가 false로 되어있어서 아래와 같은 오류가 나더라고요. 
```
Fielddata is disabled on text fields by default. 
Set fielddata=true on [your_field_name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
```

그래서 아래와 같이 ``itemId``의 ``fielddata``를 ``true``로 해준 뒤 맨 위의 집계쿼리를 썼습니다.
```
PUT activity-log-swipe/_mapping/
{
  "properties": {
    "itemId": {
      "type": "text",
      "fielddata": true
    }
  }
}
```

별 문제는 없을 것 같지만 혹시 성능이나 비용이 문제가 있을까 해서 공유드립니다!

https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#fielddata를 참고했습니다.

**Comment by ywoo-park** [comment]
@Zinyon 진영님,

일단 fielddata 값을 지금처럼 주고 혹시 만약에, 

다른 es 쿼리시에 기존 서비스 로직 요청 처리 속도에 영향을 미치는게 확인이 되면

그때 itemId를 numeric 타입으로 변경해서 인덱싱을 하는 쪽으로 결정하면 될 것 같습니다.
