### ISSUE TITLE
[reco-api] [core-api] 추천 API 개발 Phase1

### ISSUE THREAD

**Issue by ywoo-park** [ssho-lab/ssho-issue-board#37]
### 추천 API 개발 Phase1
- @Yeeun-Lee 
  - [x]  상품명 or 상품 이미지 vectorization 알고리즘 개발
  - [x] 10개의 상품 특징 벡터를 하나의 대표 특징 벡터로 변환하는 로직 구현
  - [x]  벡터간 거리계산 로직 구현

- @ywoo-park 
  - [x]  상품-회원 matrix -> 몰-회원 matrix 기반으로 CF 로직 변경 및 서비스 적용(core-api / reco-api)
  - [x]  1차 피쳐 가중치 추가

**Comment by ywoo-park** [comment]
@Yeeun-Lee 님~!

https://github.com/ssho-lab/ssho-reco-api/commit/727db3a19e2845842642da27009bda02d456cf2d

몰-회원 matrix 기반으로 로직을 변경했는데요, 기존 로직에는 응답에 mallNoList를 가중치 순서대로 정렬만해서 담았는데, 이제 각 mall의 가중치도 같이 담아야 할거 같아요! 가중치가 어떤 변수에 해당하는지 여쭤보려고 합니다~

**Comment by Yeeun-Lee** [comment]
> @Yeeun-Lee 님~!
> 
> [ssho-lab/ssho-reco-api@727db3a](https://github.com/ssho-lab/ssho-reco-api/commit/727db3a19e2845842642da27009bda02d456cf2d)
> 
> 몰-회원 matrix 기반으로 로직을 변경했는데요, 기존 로직에는 응답에 mallNoList를 가중치 순서대로 정렬만해서 담았는데, 이제 각 mall의 가중치도 같이 담아야 할거 같아요! 가중치가 어떤 변수에 해당하는지 여쭤보려고 합니다~

app.py를 기준으로는 argmax의 기준이 되는 rates가 가중치로 사용할 수 있는 변수에 해당합니다!! MF내에 존재하는 파라미터들의 경우 모델 학습을 위한 것들이기 때문에 가중치 생성에는 모델 학습 결과로 나온 rates를 사용하는 것이 합당한 것으로 보입니다!

**Comment by ywoo-park** [comment]
@Yeeun-Lee 

rates 값으로 가져왔는데, 가중치가 낮을수록 높은 우선순위의 몰이 되는게 맞을까요 예은님?

```json
   "mallNoList" : [
      "0002",
      "0003",
      "0001",
      "0004"
    ],
    "mallRateList" : [
      7.997836425355367,
      3.024118480487293,
      7.796546297826326,
      10.473284735623112
    ]
```

**Comment by Yeeun-Lee** [comment]
> @Yeeun-Lee 
> 
> 
> 
> rates 값으로 가져왔는데, 가중치가 낮을수록 높은 우선순위의 몰이 되는게 맞을까요 예은님?
> 
> 
> 
> ```json
> 
>    "mallNoList" : [
> 
>       "0002",
> 
>       "0003",
> 
>       "0001",
> 
>       "0004"
> 
>     ],
> 
>     "mallRateList" : [
> 
>       7.997836425355367,
> 
>       3.024118480487293,
> 
>       7.796546297826326,
> 
>       10.473284735623112
> 
>     ]
> 
> ```   
> 
> 
> 
> 

rates값이라면 높은 값을 가진 몰이 우선순위라고 봐야 할 것 같아요!!

**Comment by ywoo-park** [comment]
@Yeeun-Lee 

요 코드에 따라서 몰 정렬이 된건데, 그러면 어떻게 바꿔야할까요 예은님?

```python

    for key, rates in factorizer.estimated():
        sorted_idx = np.argsort(rates)
        user_item = {
            "userId": str(key),
            "mallNoList": [mall_no_list[x] for x in sorted_idx],
            "mallRateList": rates.tolist()
        }
        res_body.append(user_item)

```

**Comment by Yeeun-Lee** [comment]
> @Yeeun-Lee
> 
> 요 코드에 따라서 몰 정렬이 된건데, 그러면 어떻게 바꿔야할까요 예은님?
> 
> ```python
>     for key, rates in factorizer.estimated():
>         sorted_idx = np.argsort(rates)
>         user_item = {
>             "userId": str(key),
>             "mallNoList": [mall_no_list[x] for x in sorted_idx],
>             "mallRateList": rates.tolist()
>         }
>         res_body.append(user_item)
> ```
@ywoo-park 
```python
     for key, rates in factorizer.estimated():
         sorted_idx = np.argsort(-rates)
         user_item = {
             "userId": str(key),
             "mallNoList": [mall_no_list[x] for x in sorted_idx],
             "mallRateList": rates.tolist()
         }
         res_body.append(user_item)
 ```
위와 같이 np.argsort안에 rates앞에 -를 붙여주시면 내림차순으로 정렬됩니다!!
