### ISSUE TITLE
[reco-api] MF 값 테스트 과정에서 문의 사항

### ISSUE THREAD

**Issue by ywoo-park** [ssho-lab/ssho-issue-board#44]
추천 상품 캐시 업데이트 API를 테스트 해보다가,
조금 의문이 드는 부분을 발견해서 예은님께 여쭤보려고 합니다!

저희가 MF를 몰별 가중치 계산에 사용하고 있는데, 
아래 사진처럼 
- 스와이프 로그가 없는 경우에는 몰별 가중치가 조금씩 차이가 나게 결과가 나오고
- 스와이프 로그가 있는 경우에는 몰별 가중치가 모두 NaN으로 나오는데

혹시 이부분에 대해서 잘못된 점이 있는지,  아니면 혹시 잘 돌아가고 있다면 해당 결과가 나오는 이유를 코멘트 주실수 있으실까요~?

<img width="500" alt="mf_01" src="https://user-images.githubusercontent.com/23696493/107851419-16dc3700-6e4d-11eb-9848-870ec49ea933.PNG">

###  key: 1
<img width="400" alt="mf_02" src="https://user-images.githubusercontent.com/23696493/107851420-18a5fa80-6e4d-11eb-8202-ca5c31d6012b.PNG">

### key: 5
<img width="300" alt="mf_03" src="https://user-images.githubusercontent.com/23696493/107851423-1a6fbe00-6e4d-11eb-8557-f56a4274f338.PNG">

**Comment by Yeeun-Lee** [comment]
혹시 rating 합산 방식이 어떻게 되는지 알 수 있을까요??
- 5에 있는 117 등의 수치가 어떻게 나오게 되는 것인지 알고싶습니다!!
> 이전에 생각한 것은 스와이프로 나오는 3가지 수치를 rating으로 고려하고 그 범위 내에서의 rating을 예측하는 것으로 생각했거든요!! 근데 rating에 들어가는 값이 생각보다 너무 커서요 이 부분 확인 부탁드릴게요!!
@ywoo-park
