### ISSUE TITLE
[client-v1] 개인 정보 수정 페이지 UX 수정 및 추가 개발

### ISSUE THREAD

**Issue by ywoo-park** [ssho-lab/ssho-issue-board#50]
- 개인 정보 수정 페이지 UX 개선
- 개인 정보 수정시 사전 자동 완성 기능 추가
- 개선안에 따른 UI 추가 디자인/개발

**Comment by ywoo-park** [comment]
@Yoojin-Kim 

새로 추가한 회원정보수정 API 입니다.
수정 페이지에 해당 API 적용하시면 됩니다~!

https://github.com/ssho-lab/ssho-dev-wiki/wiki/%ED%9A%8C%EC%9B%90-%EC%A0%95%EB%B3%B4-%EC%88%98%EC%A0%95

**Comment by yoojinkimm** [comment]
@ywoo-park 

영우님 지금 로그인하면 프론트에 찍히는 로그상에서는 이름/토큰/어드민 여부 이렇게만 오고 회원 정보가 안 오는 것 같아요! 
그래서 이름만 따로 asyncStorage에 토큰이랑 저장되어 있구요.
회원 정보 수정을 하려면 정보 불러오는 api가 따로 필요할 것 같아요 ㅠ
